### ISSUE TITLE
Eligibility requirement based upon income seems wrong as it is

### ISSUE THREAD

**Issue by jeffslofish** [opensmc/get-connected-smc#11]
The current formula is 

````
 maxIncomeBasedOnNumPeople = 12060 * ((resultData.numFamilyMembers - 1) * 4180) * 1.85;
````

which produces huge numbers. What should the formula be?

**Comment by jridener** [comment]
Good question. I updated the [eligibility_requirements file](https://github.com/opensmc/get-connected-smc/blob/master/eligibility_requirements.md) last week with eligibility thresholds for all 4 eligibility levels (WIC has 2). Does that help?

One difference might be switching from annual to monthly income. GetCalFresh asks about previous month's income since income can be highly variable from month to month for those receiving food assistance.

@chaostheory: am I missing something with regard to eligibility thresholds in the eligibility requirements?

**Comment by chaostheory** [comment]
Hey John, The formula represents what you listed in the requirements. However, (hey Jeff) it is wrong. $12060 is the base income for poverty which adds $4180 for every person you add to the family. This is the correct formula for yearly calculation (feel free to correct me):
12060 + ((resultData.numFamilyMembers - 1) * 4180) * 1.85; For monthly you probably just need to divide by 12.

**Comment by chaostheory** [comment]
Before I forget, John do you want to increase Jeff's rights on this repo? I trust his submissions.

**Comment by jridener** [comment]
Done! (I think. Let me know if not).

**Comment by jeffslofish** [comment]
Can you take a look at the current state of the app and give some direction on what needs to be added or modified? I don't want to go too far in a direction that isn't desired.

**Comment by jridener** [comment]
Yes, definitely! I'm having issues getting the app started. I can't get npm
to start. It's probably due to the fact I have no idea what I'm doing and
lucked out earlier. Any help is much appreciated! Maybe a list of steps to
getting things started to review the app? Super basic here ... Thanks!

**Comment by jeffslofish** [comment]
I added a short getting started guide to the README file. Let me know if you need more than that.

**Comment by jridener** [comment]
Thanks! I'll check it out!

**Comment by jridener** [comment]
Thanks for the getting started stuff in the README file. My node/npm on Windows wasn't working correctly. I was able to get it up and running on Mac OS.

I'd like to show this to the customer at the SMC Human Services Agency for feedback too.

In the meantime, should I create new issues for questions?

**Comment by jeffslofish** [comment]
I made a slack channel for us to communicate. I figured it is best to use github mainly for actual issues with the code. You should have received an invite.

**Comment by jeffslofish** [comment]
Let me know if that doesn't work for you. Thanks!

**Comment by jridener** [comment]
I did receive the invite, thanks! We also set up a Slack channel for this on the OpenSMC Slack as well. Would you be interested in joining the OpenSMC Slack? https://opensmc.slack.com/ The channel is getconnectedsmc. Let me know if you'd rather not join the OpenSMC slack.

**Comment by jeffslofish** [comment]
Sure, can you send me an invite for it?
