### ISSUE TITLE
Should be able to get WIC without CalFresh or MediCal

### ISSUE THREAD

**Issue by jeffslofish** [opensmc/get-connected-smc#16]
Get Connected SMC feedback: Should be able to get WIC without CalFresh or MediCal (e.g. pregnant, kids under 5, income requirements)

**Comment by jridener** [comment]
Eligibility requirements here: https://github.com/opensmc/get-connected-smc/blob/master/eligibility_requirements.md

**Comment by RohitTalwalkar** [comment]
Fixed in the "some-polish-updates-before-demo" branch

**Comment by jridener** [comment]
Thanks @RohitTalwalkar!
