### ISSUE TITLE
 SMC Connect results

### ISSUE THREAD

**Issue by jeffslofish** [opensmc/get-connected-smc#19]
# Get Connected SMC feedback:

- SMC Connect results
	- Can we limit SMC Connect results to user-entered zip code only like http://www.smc-connect.org/locations?utf8=%E2%9C%93&keyword=Emergency+Food&location=94070&org_name=&service_area=smc

**Comment by saadmir** [comment]
@jridener i believe this is already done

**Comment by jridener** [comment]
@saadmir you're right! Closing now.
