### ISSUE TITLE
Final Screen issues

### ISSUE THREAD

**Issue by jeffslofish** [opensmc/get-connected-smc#24]
Get Connected SMC feedback: 
- Final screen
	- "May qualify for" . . . services
	- If qualified for CalFresh, link to (GetCalFresh site)[https://getcalfresh.org/]
	- WIC qualified, link to how (San Mateo County WIC page)[http://www.smchealth.org/wic]
	- Free/reduced price meals: link to (school district directory site)[http://www.smcoe.org/about-smcoe/districts-and-schools/]
	- If qualified for WIC, http://www.smchealth.org/wic

**Comment by RohitTalwalkar** [comment]
Do we want to hide the survey when they are on the results screen?

**Comment by jridener** [comment]
Adding home delivery for meals link: http://sanmateo.networkofcare.org/aging/services/subcategory.aspx?tax=BD-5000.3500
