### ISSUE TITLE
Form change

### ISSUE THREAD

**Issue by jridener** [opensmc/get-connected-smc#32]
On each page of the form, there's text that says "WIC." Change this text to the question title for the correct question. For example: 

Family Size
Number of Children
Household Income

**Comment by RohitTalwalkar** [comment]
Didn't seem like I could change the title for each question.  I am able to hide it, would that be better then just displaying "WIC"?

**Comment by jridener** [comment]
I think hiding for now is best. Thanks!

**Comment by RohitTalwalkar** [comment]
Cool, will do that.
