### ISSUE TITLE
Results page text change 1

### ISSUE THREAD

**Issue by jridener** [opensmc/get-connected-smc#33]
If a user doesn't qualify for any programs, replace “Sorry, you do not qualify for any of the programs” with “Your income does not meet the eligibility requirements for the Federal Food Programs but here are local food resources”

**Comment by RohitTalwalkar** [comment]
Will be updated once we merge this branch:
https://github.com/opensmc/get-connected-smc/commits/some-polish-updates-before-demo

**Comment by RohitTalwalkar** [comment]
@jridener - any chance you have an image to go with "Your income does not meet the eligibility requirements for the Federal Food Programs but here are local food resources" ?

**Comment by jridener** [comment]
I'll look for one and add it to the repo in the icons directory. I'll link
to it here in the issue.

**Comment by jridener** [comment]
Ran in to some issues with the County network policy in downloading a picture. Will get one posted tonight

**Comment by jridener** [comment]
Image to use for results page when a user does not qualify for any programs: https://github.com/opensmc/get-connected-smc/blob/master/icons/Life-Perseverance-Bricks-Nature-Determination-335446.jpg

**Comment by RohitTalwalkar** [comment]
Great, thanks - added into the app on the update branch:
![image](https://user-images.githubusercontent.com/22007195/30199230-a801cd30-9426-11e7-9ee6-35dc584c13cf.png)

**Comment by jridener** [comment]
Looks great! Thanks! We can close out this issue when the branch is merged.
