### ISSUE TITLE
Users Without Kids Eligible for WIC and Free/Reduced Price School Lunches

### ISSUE THREAD

**Issue by jridener** [opensmc/get-connected-smc#40]
If a user responds that they do not have children, the results screen still shows that they may be eligible for WIC and free/reduced price school lunches.

Pregnant women with no other children are eligible for WIC, but users without children should not see free/reduced price school lunch. 

Can we change the logic for WIC and free/reduced price lunch to something like
	• Change logic for free/reduced price school lunches to number of kids > 0
	• Change logic for WIC to kids 5 or under > 0 OR pregnant YES OR pregnant YES AND kids 5 or under > 0

Feedback from the End Hunger Task Force

**Comment by RohitTalwalkar** [comment]
@jridener - taking a look into the logic - one thing I noticed is that we only show the "How many children total are in your household?" question if "Are there any children in your household?" is "yes".

Since that's the case, I don't think we should show "0" as an option, it should start with "1".

![image](https://user-images.githubusercontent.com/22007195/37139232-f7e7abfc-2261-11e8-81a7-6d9b1ccc1c7c.png)

**Comment by RohitTalwalkar** [comment]
Any thoughts?

**Comment by RohitTalwalkar** [comment]
Also, same for "How many people live in your household, including yourself":
![image](https://user-images.githubusercontent.com/22007195/37139884-78e390b6-2264-11e8-94d5-5f8ed9aebe6f.png)

**Comment by jridener** [comment]
Agree! 

There's no reason to show 0 at all. I would hope there is at least one person in a household for people who use the site. Since the children question is if/then, there's also no reason to have a 0 option.

Thanks for catching this!

**Comment by RohitTalwalkar** [comment]
@jridener - the code that fixes this isn't merged it :-|

**Comment by RohitTalwalkar** [comment]
Should be fixed by this PR:
https://github.com/opensmc/get-connected-smc/pull/57

Once merged and updated, @jridener - could you test a few of the survey cases?  I gave a few a try to make sure I didn't break anything, but, another set of eyes would be great.
