### ISSUE TITLE
Open Resource Links in a New Window

### ISSUE THREAD

**Issue by jridener** [opensmc/get-connected-smc#41]
At the end of the form if a user clicks on a resource link then returns to the end of the form to click on another resource link, the form has reset to the beginning.

Can resource links be set to open in a new window?

Feedback from End Hunger Task Force

**Comment by RohitTalwalkar** [comment]
@saadmir - sorry, ended up accidentally pushing to the remote master :-(
https://github.com/opensmc/get-connected-smc/commit/1eadb5d74c3c3973702c066f63c0e42fa19cb795

**Comment by RohitTalwalkar** [comment]
This will be fixed once we deploy
