### ISSUE TITLE
Add Second Harvest Food Bank contact info at the top of results screen

### ISSUE THREAD

**Issue by jridener** [opensmc/get-connected-smc#44]
Add information for immediate help with food to the top of every results screen

## Need help getting food now?
 
Call Food Connection at 1-800-984-3663
	    Monday - Friday, 8:00 am - 5:00 pm.
	    Staff members speak English, Spanish, Vietnamese, Chinese (Cantonese and Mandarin), and Tagalog. Three-way interpretation is available for other languages.
	
Call 211 after hours
	    24/7, free, confidential, available in multiple languages. Operated by United Way Bay Area.

Email Food Connection at foodconnection@shfb.org.

Text "Web Connect" at 408-455-5181

Feedback from End Hunger Task Force

**Comment by RohitTalwalkar** [comment]
Took a shot at adding the info, though, now the "Getting food on the table..." stuff seems a bit odd:
![image](https://user-images.githubusercontent.com/22007195/35374062-27929eb6-0156-11e8-816c-0cbfac4859e2.png)

**Comment by jridener** [comment]
@RohitTalwalkar I think it's fine. The language on the top is there from the start of the form. Would hiding it on the results screen be difficult?

**Comment by RohitUdayTalwalkar** [comment]
Okay, I'll work to hide the text "Get help putting food on the table" + "See which...."

**Comment by RohitUdayTalwalkar** [comment]
Okay, got the "Get help..." text hidden on the final results screen:

![image](https://user-images.githubusercontent.com/5178749/37137043-f1d1b9f0-2258-11e8-8771-445b67cc0cf7.png)

**Comment by RohitTalwalkar** [comment]
PR is open:
https://github.com/opensmc/get-connected-smc/pull/55
