### ISSUE TITLE
Update WIC eligibility text in results screen

### ISSUE THREAD

**Issue by jridener** [opensmc/get-connected-smc#45]
Currently users see "You are eligible for WIC" in the results screen when they qualify for the program.

Change the text to "You may be eligible for WIC" 

Feedback from End Hunger Task Force

**Comment by RohitTalwalkar** [comment]
@jridener - should we also change to "You may adjunctly qualify for WIC"?

**Comment by jridener** [comment]
I think leaving it at "may be eligible" is good enough. I don't want to introduce any confusion to users. They will want to contact the program for more info either way (fully or adjunctively eligible)

**Comment by RohitTalwalkar** [comment]
Ah, good point, will update now.

**Comment by RohitTalwalkar** [comment]
Also, chatted in Slack - we'll combine both the WIC and adjunct into a single result; should result in less confusion and lets us simplify the logic + task force has not asked for adjunctive eligibility result.

**Comment by RohitTalwalkar** [comment]
Changes are in #58
