### ISSUE TITLE
New icons for programs on results page

### ISSUE THREAD

**Issue by jridener** [opensmc/get-connected-smc#49]
The current plate and utensils icon on the results page for CalFresh is too small compared to the others and looks too much like the Second Harvest Food Bank logo.

Feedback from End Hunger Task Force

**Comment by RohitTalwalkar** [comment]
@jridener - it'll take ~1 min to swap out, do you have another icon for us?

**Comment by jridener** [comment]
I'll work on it today. Thanks for checking!

**Comment by RohitTalwalkar** [comment]
Yay,  thanks!

**Comment by jridener** [comment]
https://www.211oc.org/images/CalFresh.png

I'm mobile at the moment so I have no idea if this works or not. Let me know if I doesn't work at all

**Comment by RohitTalwalkar** [comment]
How's this look (made it 700 x 700 to match the other icons and "center" it a bit)
![image](https://user-images.githubusercontent.com/22007195/35189741-65cf32e6-fe06-11e7-84e6-19c499cf8bd3.png)

**Comment by RohitTalwalkar** [comment]
Though, maybe it should be B/W - the other icons don't look as great :-P

**Comment by jridener** [comment]
@RohitTalwalkar You're right. I'll look for better images for the other programs as well. WIC has a program-wide image and I can find something better for the school programs and senior meal delivery

**Comment by jridener** [comment]
Changed issue to add new, color icons for each program. New images attached to this comment.

We can use SMCOE_logo.jpg for both free and reduced price lunch at school

With the short explanations of each program from #50 I think these will be effective
![smc_mow_logo_0](https://user-images.githubusercontent.com/823651/35190943-1a22ca98-fe23-11e7-8d3e-8697343a4a60.png)
![wic_ca](https://user-images.githubusercontent.com/823651/35190944-1a5b5f7a-fe23-11e7-9f09-a3d4e331097b.png)
![smcoe_logo](https://user-images.githubusercontent.com/823651/35190945-1a79f688-fe23-11e7-94e9-6d4efa78ada4.jpg)

**Comment by RohitTalwalkar** [comment]
I did some slight adjustments on the images, how do they look?
![image](https://user-images.githubusercontent.com/22007195/37506359-b9dafd3c-28a6-11e8-8d3c-ce41831ac3de.png)

**Comment by RohitTalwalkar** [comment]
hmm, nm, the CalFresh alignment is off a bit...I'll try to get them the same dimensions so the text lines up.

**Comment by RohitTalwalkar** [comment]
Okay, things line up better (not perfect...but, lets ship!)
![image](https://user-images.githubusercontent.com/22007195/37560532-5e8dffd6-29f7-11e8-9f91-63bcf304cc93.png)

**Comment by jridener** [comment]
Agreed! If they want perfect, they can supply size-aligned images. This looks great!

**Comment by RohitTalwalkar** [comment]
@saadmir - fixed in #60
