### ISSUE TITLE
Create queries for user zip code and food tag from Ohana API

### ISSUE THREAD

**Issue by jridener** [opensmc/get-connected-smc#5]
When a user completes the form, they will receive information on how to get immediate food help from food banks and other places that will help them access food. This information will be based on the zip code they entered in the form and the tag "food" on [SMC Connect](http://www.smc-connect.org/)

The Ohana API documentation can be found on [Code for America's Github page](http://codeforamerica.github.io/ohana-api-docs/)

**Comment by jeffslofish** [comment]
Hi! I'd be interested in working on this.

**Comment by jridener** [comment]
@jeffslofish Awesome! I sent you an invite to collaborate on the repo. Please let me know if you have any questions

**Comment by RohitTalwalkar** [comment]
@jridener - it looks like we want to use the "category" field to filter things (based off my poking around in the API docs, as it uses these categories - https://about.auntbertha.com/openeligibility)

Here's the results I get when I make that change and search 94402
http://www.jsoneditoronline.org/?id=dfc09e5c967ed0ab3bb3e1da51e67af7 

Could you take a look and see if they are better?

**Comment by jridener** [comment]
@RohitTalwalkar this is a huge improvement! We can work with our County Human Service Agency (HSA) contacts to tweak the results for specifically what they want to see in these results. For example, they may want just food banks.
