### ISSUE TITLE
Short program descriptions on results page

### ISSUE THREAD

**Issue by jridener** [opensmc/get-connected-smc#50]
When users are trying to prioritize what programs from the results page to contact first, they may not understand the populations served by each program. 

To help users prioritize programs they may be eligible for, add very short descriptions of programs in/under program icons on results page

Cal Fresh : Family/food
Home delivery of meals for seniors : Older adults
WIC : Women and Children
Free meals at school: School age children
Reduced price meals at school : School age children

Feedback from End Hunger Task Force

**Comment by RohitTalwalkar** [comment]
Added some captions, can you confirm if this is what you were thinking?
![image](https://user-images.githubusercontent.com/22007195/35373115-0620a164-0152-11e8-851c-7cf91344af1e.png)

**Comment by jridener** [comment]
@Rohit yes, definitely. Maybe bold and a slightly larger font like 24 point (if other text is 21).

**Comment by RohitTalwalkar** [comment]
Cool, how's this?
![image](https://user-images.githubusercontent.com/22007195/35373834-2e528686-0155-11e8-9b7a-14d6f5406bb2.png)

**Comment by jridener** [comment]
I think that's great. We can send it back to the task force for further comment. Thanks!

**Comment by rohit** [comment]
Folks, I'm not the Rohit you'll are looking for. Please stop tagging me!

**Comment by RohitTalwalkar** [comment]
@jridener @saadmir - this is also fixed in PR #52 
https://github.com/opensmc/get-connected-smc/pull/52
